### ISSUE TITLE
header_exclude bug

### ISSUE THREAD

**Issue by leemannd** [camptocamp/anthem#24]
Hello, songs have been exported for the mtsmte project.
I'm facing a lot of import errors because anthem is trying to exclude header that is not present. https://github.com/camptocamp/anthem/blob/master/anthem/lyrics/loaders.py#L93
`    Import res.partner from csv: error
main: error
Traceback (most recent call last):
  File "/usr/local/bin/anthem", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/anthem/cli.py", line 59, in main
    run(odoo_args, args.target, options)
  File "/usr/local/lib/python2.7/dist-packages/anthem/cli.py", line 88, in run
    func(ctx)
  File "/usr/local/lib/python2.7/dist-packages/anthem/output.py", line 72, in decorated
    return func(*args, **kwargs)
  File "/opt/odoo/songs/install/generated/stock.py", line 158, in main
    load_res_partner(ctx)
  File "/usr/local/lib/python2.7/dist-packages/anthem/output.py", line 72, in decorated
    return func(*args, **kwargs)
  File "/opt/odoo/songs/install/generated/stock.py", line 137, in load_res_partner
    load_csv(ctx, 'data/install/generated/res.partner.csv', model, header_exclude=header_exclude)  # noqa
  File "/opt/odoo/songs/common.py", line 23, in load_csv
    header=header, header_exclude=header_exclude)
  File "/usr/local/lib/python2.7/dist-packages/anthem/lyrics/loaders.py", line 93, in load_csv_stream
    pop_idxs = [_header.index(x) for x in header_exclude]
ValueError: 'self/id' is not in list
`

We should update this in order not to have an error while trying to remove an unexisting header.

**Comment by simahawk** [comment]
it's a bug in dj tool https://github.com/camptocamp/odoo-prototype/issues/65
